### PR TITLE
Add Group Expense Flow

### PR DESCRIPTION
**Pull request by Harin329**

### CODE REVIEW

**Review by Abeilles14 — COMMENTED** [review]
Wren and I figured out the groupExpenseObj Model in My PR the other day, the way the backend endpoint was structured is to be able to split the group expense into payments was to have an array of tuples containing each user_id and their individual amount owed, for example:

```
{
   "fk_group_id" : 1,
   "fk_added_by_id" : "zhxcuiashui2442",
   "fk_currency_id" : 1,
   "expense_name" : "Tison group expense 3",
   "is_archived" : 0,
   "amount" : 400.0000,
   "user_amounts" : [
       {
       "fk_sender_id" : "r3j24qurhfsjdf",
       "amount" : "150.0000"
       },
       {
       "fk_sender_id" : "r3289qhfwui",
       "amount" : "250.0000"
       }
   ]
}
```

The createGroupExpense route would likely never be used (didn't want to remove it yet just in case though) since we are using the splitGroupExpense http://localhost:8000/group_expense/splitGroupExpense route instead to deal with the payments in the same go, and inside that mega endpoint, the createGroupExpense and createPayment functions would be called one after the other.

**Comment by Abeilles14** [comment]
Although I just realized that might cause some issues in the front end models if we try to get just a regular group expense without the amounts or anything for example getGroupExpenseByGroupId, since that would return something in the format of:
```
{
       "expense_id": 1,
       "fk_group_id": 1,
       "fk_added_by_id": "zhxcuiashui2442",
       "fk_currency_id": 1,
       "expense_name": "Ailn group expense",
       "is_archived": 0,
       "amount": 100
   }
```
This one would simply return the group expense object without all the individual payment data

**Comment by wrenliang** [comment]
> Wren and I figured out the groupExpenseObj Model in My PR the other day, the way the backend endpoint was structured is to be able to split the group expense into payments was to have an array of tuples containing each user_id and their individual amount owed, for example:
> 
> ```
> {
>    "fk_group_id" : 1,
>    "fk_added_by_id" : "zhxcuiashui2442",
>    "fk_currency_id" : 1,
>    "expense_name" : "Tison group expense 3",
>    "is_archived" : 0,
>    "amount" : 400.0000,
>    "user_amounts" : [
>        {
>        "fk_sender_id" : "r3j24qurhfsjdf",
>        "amount" : "150.0000"
>        },
>        {
>        "fk_sender_id" : "r3289qhfwui",
>        "amount" : "250.0000"
>        }
>    ]
> }
> ```
> 
> The createGroupExpense route would likely never be used (didn't want to remove it yet just in case though) since we are using the splitGroupExpense http://localhost:8000/group_expense/splitGroupExpense route instead to deal with the payments in the same go, and inside that mega endpoint, the createGroupExpense and createPayment functions would be called one after the other.

@Abeilles14 Looks like Harin is calling the createGroupExpense endpoint directly and making all the child payments in separate calls. The functionality is the same, so I'm just gonna approve this PR now and we can change it to the splitGroupExpense endpoint later if needed

**Review by wrenliang — APPROVED** [review]

**Comment by Abeilles14** [comment]
Ah ok sounds good, I'll merge my PR first so that Harin can keep his changes and update the model

**Pull request merged**
