### PR TITLE
Backend Cleanup

### PR DESCRIPTION
**Pull request by mebesius**
Pretty straightforward PR. Will look into setting up `Jest` later this week but thought it would be helpful for everyone's work this week if everyone had access to `ESLint` / `Prettier` since we merged a lot of work into `main` recently. 

- Add `ESLint`, `Prettier` for enforcing code standards/styling
- Rename files for consistent file naming
- Update `import` / `require` statements to reflect name changes
- Remove unused SQL table files

We can see the updates to the file names below as well as the `require` and `import` statements. `Prettier` is run via a `ESLint` plugin which is all run together with `npm run lint` once new dependencies are installed locally after pulling the code from this PR. No errors other than the existing finickiness of the server trying to connect without SQL were experienced in Docker.

### CODE REVIEW

**Review by Harin329 — DISMISSED** [review]
Branch works fine, not sure about the conflicts though

**Comment by wrenliang** [comment]
Looks fine to me, thoughts @Abeilles14? I think most of this is your code so you should have final say over the changes

**Comment by Abeilles14** [comment]
@mebesius So the usual naming convention I've always been taught for naming these kinds of files is <file_name>-<file description> (always in singular), just so that we can clearly differentiate the context of the file and the "type" of code it contains, so for example group_expense would have an underscore since the _ just represents a space in the name, and the dash in group_expense-service or group_expense-route kinda represents what the code contains if that makes sense.
I did make a mistake with the group_routes naming though, oops!
As long as there's some kind of constant pattern like there is now using all dashes, that's good though, it doesn't matter so don't worry about changing anything!

About single quotes ' ' vs double quotes " " for strings, I usually prefer double quotes, but it's just a matter of preference, in the end I guess it doesn't matter as long as everything is consistent, I'll try to remember.
Looks good to me, thanks for running running through the code!
Good to merge once the conflicts are resolved.

**Comment by Abeilles14** [comment]
I fixed all the conflicts in the PR, I accepted all incoming changes from main that Harin made, everything seems to run fine. Might want to check again just in case and approve again @Harin329 @wrenliang

**Comment by mebesius** [comment]
> 
> 
> @mebesius So the usual naming convention I've always been taught for naming these kinds of files is <file_name>- (always in singular), just so that we can clearly differentiate the context of the file and the "type" of code it contains, so for example group_expense would have an underscore since the _ just represents a space in the name, and the dash in group_expense-service or group_expense-route kinda represents what the code contains if that makes sense.
> I did make a mistake with the group_routes naming though, oops!
> As long as there's some kind of constant pattern like there is now using all dashes, that's good though, it doesn't matter so don't worry about changing anything!
> 
> About single quotes ' ' vs double quotes " " for strings, I usually prefer double quotes, but it's just a matter of preference, in the end I guess it doesn't matter as long as everything is consistent, I'll try to remember.
> Looks good to me, thanks for running running through the code!
> Good to merge once the conflicts are resolved.

@Abeilles14 , I think the file naming convention is just kind of one of those things that is a "house rule" for lack of a better term, so I just went with what I was familiar with. For quotes, as long as we agree to stick with one kind, it's fine, and `Prettier` will help us ensure consistency on the back-end going forward. I put single quotes in the `Prettier` configuration for now just because it's one less keystroke for the majority of strings.

**Review by Abeilles14 — APPROVED** [review]

**Comment by Abeilles14** [comment]
LGTM, might want to wait for @Harin329 to approve again though

**Review by wrenliang — APPROVED** [review]

**Pull request merged**
