### PR TITLE
Ios/firebase setup

### PR DESCRIPTION
**Pull request by Harin329**
Facebook Login + Email Login + FCM Token

### CODE REVIEW

**Comment by Harin329** [comment]
@yan-alan @wrenliang Do either of you know how to solve this merge conflict? Should it just be an accept both for this? Never had conflicts with pbxproj before....

**Comment by wrenliang** [comment]
Looks like the only conflicts you can't accept both are with the Pods_dough_bros_ios files. My guess is to manually resolve those ones and take both for everything else. Thoughts @yan-alan?

**Review by yan-alan — APPROVED** [review]
Alright I fixed conflicts should be good to merge

**Comment by yan-alan** [comment]
Just normally take unions and then if you see duplicates for pod files just take your branch version

**Comment by Harin329** [comment]
Thanks guys!

**Pull request merged**
