### PR TITLE
Ios/all around dev

### PR DESCRIPTION
**Pull request by Harin329**
Sorry code quality was probably deteriorating as time went, have to study for finals so not sure how much time i'll have to work on it rest of week so its a speedrun. Let me know if there's any glaring errors / things you want me to fix please!

### CODE REVIEW

**Comment by mebesius** [comment]
I can't speak to the iOS code because I am not familiar with iOS but the SQL and server code looks good. I am not 100% on the `p.` syntax in one of the SQL files as a shorthand it seemed to be. Maybe @Abeilles14 or @wrenliang can confirm that's sound? Otherwise, the SQL and server code looks good to me. Happy to see mock data added :)

**Comment by wrenliang** [comment]
> I can't speak to the iOS code because I am not familiar with iOS but the SQL and server code looks good. I am not 100% on the `p.` syntax in one of the SQL files as a shorthand it seemed to be. Maybe @Abeilles14 or @wrenliang can confirm that's sound? Otherwise, the SQL and server code looks good to me. Happy to see mock data added :)

Yep the `p` alias is done correctly

**Review by wrenliang — DISMISSED** [review]

**Comment by Abeilles14** [comment]
LGTM!

**Review by Abeilles14 — DISMISSED** [review]
LGTM!

**Review by wrenliang — APPROVED** [review]

**Pull request merged**
